-- Ferriol OS · Los DOS fundadores SON los administradores empresa (no hay otro rol aparte)
-- Cada persona (ej. vos y tu hermano) = usuario en Authentication + fila en public.profiles con role = 'super', active true, trial_ends_at (cuenta regresiva; al vencer, la app bloquea esa sesión como con kioscos).
-- Si no renovás trial_ends_at: la app marca active = false y no deja entrar hasta actualizar perfiles.
--
-- PASOS MANUALES
-- 1) Authentication → crear EXACTAMENTE DOS usuarios (los dos fundadores como administradores).
-- 2) Copiar cada UUID desde auth.users.
-- 3) Sustituir UUID_... y emails en el INSERT; ejecutar una sola vez.
--
-- Vigencia de ejemplo: 365 días desde ahora UTC (cambiá interval o fijá una fecha ISO).

-- Descomenta y adapta antes de ejecutar:

-- INSERT INTO public.profiles (
--   id,
--   email,
--   role,
--   active,
--   trial_ends_at
-- ) VALUES
-- (
--   'UUID_FUNDADOR_1'::uuid,
--   'fundador1@tu-dominio.com',
--   'super',
--   true,
--   ((now() AT TIME ZONE 'utc') + interval '365 days')
-- ),
-- (
--   'UUID_FUNDADOR_2'::uuid,
--   'fundador2@tu-dominio.com',
--   'super',
--   true,
--   ((now() AT TIME ZONE 'utc') + interval '365 days')
-- );

-- Renovación rápida (cuando llegue la fecha o antes):
-- UPDATE public.profiles SET active = true, trial_ends_at = ((now() AT TIME ZONE 'utc') + interval '180 days') WHERE id = 'UUID'::uuid AND role = 'super';
